### PR TITLE
Update Figure 3a

### PR DESCRIPTION
**Pull request by snuesslein**
Changed the color of boundaries to indicate ||\tilde{b}-b||_1 using a colormap
See attached file:
[stab_dp5.pdf](https://github.com/ketch/Positive_RK_Reproducibility/files/5949852/stab_dp5.pdf)

### CODE REVIEW

**Comment by ketch** [comment]
That looks good.  In my opinion, you could also remove the diagonal lines as they are distracting and I think it's clear what is the "inside" of the stability region even without them.

**Comment by ranocha** [comment]
:+1: Could you also please make a PR to the original repo (with the change suggested by @ketch) to update the manuscript, @snuesslein?

**Comment by snuesslein** [comment]
Just as a clarification: Should I remove all the diagonal lines? There are two options:

1. Remove only the diagonal lines for the adapted method and keep it for the original method. This would still give an indication on the inside/outside. But the plot would be not as filled.
hatch

2. Remove all the diagonal lines. Then it might also be useful to remove them for the plot for the implicit method.
nohatch

**Comment by ketch** [comment]
I recommend removing them all from both plots.  For me, that makes it much easier to see what is important in the plots.  I think the target audience is familiar enough with these types of plots that it will be clear.

One other thing I like to do is use an aspect ratio of 1 and make sure the real axis falls exactly in the middle of the plot (vertically).

**Comment by ketch** [comment]
@snuesslein It looks like you already made these changes in a direct commit to master.  So shall I close this PR?

**Comment by snuesslein** [comment]
I already changed the plots, but I am not able to change the code in this repository, so you still have to merge the pull request.

**Pull request merged**
